---
title: Honey Syal
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  evants:
    title: evants
    output: true
  news:
    title: news
    output: true
gem: jekyll-sitemap
